title: Container Desktop Entries Docs
description: Documentation for Container Desktop Entries
theme: just-the-docs

url: https://ryanabx.github.io/container-desktop-entries

aux_links:
  GitHub: https://github.com/ryanabx/container-desktop-entries
